name: eCFR Sync

on:
    schedule:
        - cron: "0 */3 * * *"
    workflow_dispatch:

jobs:
    check-and-sync:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libcurl4-openssl-dev libpugixml-dev cmake build-essential jq

            - name: Get latest eCFR date
              id: check-date
              run: |
                  echo "Full API response:"
                  curl -s https://www.ecfr.gov/api/versioner/v1/titles.json | jq '.'

                  LATEST_DATE=$(curl -s https://www.ecfr.gov/api/versioner/v1/titles.json | jq -r '.meta.date')
                  echo "Latest date from API: $LATEST_DATE"

                  if [ -d "public/ecfr" ]; then
                    LOCAL_DATE=$(ls public/ecfr | sort -r | head -n1)
                    echo "Most recent local date: $LOCAL_DATE"
                  else
                    LOCAL_DATE="1970-01-01"
                    echo "No local data found, using default date: $LOCAL_DATE"
                  fi

                  echo "latest_date=$LATEST_DATE" >> $GITHUB_OUTPUT
                  echo "local_date=$LOCAL_DATE" >> $GITHUB_OUTPUT

                  if [ "$LATEST_DATE" != "$LOCAL_DATE" ]; then
                    echo "Update needed: $LOCAL_DATE -> $LATEST_DATE"
                    echo "needs_update=true" >> $GITHUB_OUTPUT
                  else
                    echo "No update needed, already at latest date"
                    echo "needs_update=false" >> $GITHUB_OUTPUT
                  fi

            - name: Build downloader
              if: steps.check-date.outputs.needs_update == 'true'
              run: |
                  mkdir build
                  cd build
                  cmake ..
                  make

            - name: Run downloader
              if: steps.check-date.outputs.needs_update == 'true'
              run: |
                  cd build
                  ./ecfr_downloader "${{ steps.check-date.outputs.latest_date }}"

            - name: Commit and push if changed
              if: steps.check-date.outputs.needs_update == 'true'
              run: |
                  git config --global user.name 'GitHub Action'
                  git config --global user.email 'action@github.com'
                  git add public/ecfr
                  git commit -m "Update eCFR data to ${{ steps.check-date.outputs.latest_date }}"
                  git push

            - name: Install Vercel CLI
              if: steps.check-date.outputs.needs_update == 'true'
              run: npm install --global vercel@latest

            - name: Deploy to Vercel
              if: steps.check-date.outputs.needs_update == 'true'
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
              run: |
                  vercel pull --yes --environment=production --token=$VERCEL_TOKEN
                  vercel build --prod --token=$VERCEL_TOKEN
                  vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
